name: k6 performance test

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Instalar k6
        run: |
          curl -s https://packagecloud.io/install/repositories/grafana/stable/script.deb.sh | sudo bash
          sudo apt-get install -y k6

      - name: Ejecución de las pruebas de carga
        run: k6 run test.js